language: java
jdk: oraclejdk8
after_success:
    rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress /target/configservice.jar canaban.ddns.net:/canaban/configservice