server:
  port: 8004
spring:
    application:
        name: configservice
    cloud:
        config:
             server:
                 git:
                     uri: https://github.com/GusevAnton/config
    boot:
        admin:
            url: http://localhost:8010
logging:
    file: logs/ConfigService.log
    level: debug
eureka:
  client:
    service-url:
      defaultZone: http://canaban.ddns.net:8004/eureka
    eureka-connection-idle-timeout-seconds: 1